import { MenuItem } from '@/types';

export const mockMenuItems: MenuItem[] = [
  // BARBEQUE kababs
  {
    id: '1',
    name: 'Murgh Malai Kabab',
    description: 'Tender chicken marinated in cream and mild spices, grilled to perfection',
    price: 100,
    category_id: 'kababs',
    type_id: 'non-veg',
    image_url: '/MalaiKabab.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 80,
    preparation_time: 20,
    pre_order_time: 1,
    is_available: true,
    is_featured: true,
    featured_priority: 1,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Chicken Tikka Kabab',
    description: 'Succulent chicken pieces marinated in yogurt and spices, charcoal grilled',
    price: 100,
    category_id: 'kababs',
    type_id: 'non-veg',
    image_url: '/Sheekh.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 80,
    preparation_time: 20,
    pre_order_time: 1,
    is_available: true,
    is_featured: true,
    featured_priority: 2,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Chicken Haryali Kabab',
    description: 'Green herb marinated chicken kebab with mint and coriander',
    price: 100,
    category_id: 'kababs',
    type_id: 'non-veg',
    image_url: '/HaryaliKabab.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 80,
    preparation_time: 20,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Chicken Seekh Kebab',
    description: 'Minced chicken with spices and herbs, molded on skewers and grilled',
    price: 100,
    category_id: 'kababs',
    type_id: 'non-veg',
    image_url: '/ChickenSheek.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 75,
    preparation_time: 20,
    pre_order_time: 1,
    is_available: true,
    is_featured: true,
    featured_priority: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // BBQ CHICKEN WRAPS
  {
    id: '5',
    name: 'Chicken Tikka Wrap',
    description: 'Tender chicken tikka wrapped in soft bread with fresh herbs',
    price: 120,
    category_id: 'wraps',
    type_id: 'non-veg',
    image_url: '/TikkaWrap.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 60,
    preparation_time: 15,
    pre_order_time: 1,
    is_available: true,
    is_featured: true,
    featured_priority: 4,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Sheek Roll',
    description: 'Spiced minced meat wrapped in thin bread',
    price: 120,
    category_id: 'wraps',
    type_id: 'non-veg',
    image_url: '/SheeksRoll.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 50,
    preparation_time: 15,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Malai Chicken Wrap',
    description: 'Creamy marinated chicken in soft wrap with fresh vegetables',
    price: 120,
    category_id: 'wraps',
    type_id: 'non-veg',
    image_url: '/MalaiWrap.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 55,
    preparation_time: 15,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Haryali Chicken Wrap',
    description: 'Green herb marinated chicken with mint sauce in a wrap',
    price: 120,
    category_id: 'wraps',
    type_id: 'non-veg',
    image_url: '/HaryaliWrap.png',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 50,
    preparation_time: 15,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // BBQ CHICKEN HOTDOG
  {
    id: '9',
    name: 'BBQ Chicken Hotdog',
    description: 'Juicy BBQ chicken in a soft hotdog bun with fresh toppings',
    price: 80,
    category_id: 'hotdog',
    type_id: 'non-veg',
    image_url: '/BBQHotdog.png',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 80,
    preparation_time: 10,
    pre_order_time: 1,
    is_available: true,
    is_featured: true,
    featured_priority: 5,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // SAUSY DELICACIES
  {
    id: '10',
    name: 'Chicken Lollipop',
    description: 'Tender chicken drumsticks fried until crispy and golden',
    price: 130,
    category_id: 'delicacies',
    type_id: 'non-veg',
    image_url: '/Lollipop.jpeg',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 15,
    stock_quantity: 70,
    preparation_time: 20,
    pre_order_time: 1,
    is_available: true,
    is_featured: true,
    featured_priority: 6,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '11',
    name: 'Boneless Chicken Manchurian',
    description: 'Crispy boneless chicken in tangy Manchurian sauce',
    price: 120,
    category_id: 'delicacies',
    type_id: 'non-veg',
    image_url: '/ChickenManchurian.png',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 60,
    preparation_time: 18,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // ROYAL DESSERTS
  {
    id: '12',
    name: 'Oh My Gourd',
    description: 'A healthy and energetic refreshing pumpkin drink',
    price: 100,
    category_id: 'desserts',
    type_id: 'veg',
    image_url: '/OhMyGourd.png',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 50,
    preparation_time: 10,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '13',
    name: 'Almond & Kaddu Ki Kheer',
    description: 'Perfect blend of condensed milk, pumpkin, saffron, khova and sugar, garnished with almonds and pistachios',
    price: 100,
    category_id: 'desserts',
    type_id: 'veg',
    image_url: '/KadduKiKheer.png',
    unit_type: 'piece',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 45,
    preparation_time: 15,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const categoryNames: Record<string, string> = {
  'kababs': 'Barbeque Kababs',
  'wraps': 'BBQ Chicken Wraps',
  'hotdog': 'BBQ Chicken Hotdog',
  'delicacies': 'Sausy Delicacies',
  'desserts': 'Royal Desserts',
};

export const typeNames: Record<string, { name: string; color: string }> = {
  'veg': { name: 'Veg', color: '#22C55E' },
  'non-veg': { name: 'Non-Veg', color: '#EF4444' },
  'egg': { name: 'Egg', color: '#F59E0B' },
  'vegan': { name: 'Vegan', color: '#10B981' },
};